"""Fixed-input hashes generated by unmodified jury semantics, native execution only."""
import hashlib
import json
import tempfile
import unittest
from datetime import UTC, datetime
from pathlib import Path
from unittest.mock import patch
from uuid import UUID

from nonzero_cloudops import NonZeroCloudOpsService, module_descriptor
from nonzero_cloudops.contract import JUDGE_SHA


def identifier(number):
    return UUID(f'00000000-0000-7000-8000-{number:012x}')


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, separators=(',', ':'), ensure_ascii=True).encode()).hexdigest()


@unittest.skipUnless(module_descriptor()['available'], 'native nonzero extra is not installed')
class NativeReferenceParityTests(unittest.TestCase):
    def test_fixed_evidence_proposal_approval_receipt_and_verification_hashes(self):
        oracle = json.loads((Path(__file__).parent/'fixtures/nonzero_parity_v1.json').read_text())
        self.assertEqual(oracle['source_sha'], JUDGE_SHA)
        self.assertEqual(len(oracle['vectors']), 5)
        now = datetime(2026, 9, 12, 12, tzinfo=UTC)
        for vector in oracle['vectors']:
            with self.subTest(target=vector['resource_id'], decision=vector['decision']), tempfile.TemporaryDirectory() as folder:
                service = NonZeroCloudOpsService(Path(folder)/'native', clock=lambda: now)
                try:
                    service.components.investigation._proposal_id_factory = lambda: identifier(4)
                    service.components.execution._request_id_factory = lambda: identifier(5)
                    service.components.execution._nonce_factory = lambda: 'synthetic-'+'n'*32
                    with patch('nonzero_cloudops.models.generate_run_id', return_value=identifier(1)), \
                         patch('nonzero_cloudops.models.generate_trace_id', side_effect=[identifier(2), identifier(3)]):
                        code, result = service.request('POST', '/api/runs', {key: vector[key] for key in ('resource_type', 'resource_id')}, operator=True)
                    self.assertEqual(code, 201)
                    first = result['result']
                    material = {'initial': first}
                    self.assertEqual(first['final_state'], vector['initial_state'])
                    if vector['decision'] is not None:
                        path = '/api/runs/'+first['run_id']
                        code, challenge = service.request('POST', path+'/approval-request', {}, operator=True)
                        self.assertEqual(code, 200)
                        challenge = challenge['result']
                        # Domain record includes nullable fields in the original request dump.
                        request = service.components.repository.get_checkpoint(identifier(1)).local_approval_request.model_dump(mode='json')
                        fields = ('request_id', 'run_id', 'proposal_id', 'request_hash', 'proposal_hash', 'evidence_hash', 'proposal_version')
                        body = {**{key: request[key] for key in fields}, 'decision': vector['decision'],
                                'decision_nonce': challenge['decision_nonce']}
                        code, resolution = service.request('POST', path+'/decision', body, operator=True)
                        self.assertEqual(code, 200)
                        code, completion = service.request('POST', path+'/resume', {'confirm_execution': True}, operator=True)
                        self.assertEqual(code, 200)
                        material.update(request=request, resolution=resolution['result'], completion=completion['result'])
                    self.assertEqual(service.components.executor.mutation_calls, vector['mutation_count'])
                    self.assertEqual({name: digest(value) for name, value in material.items()}, vector['record_sha256'])
                finally:
                    service.close()


if __name__ == '__main__':
    unittest.main()
